// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: proto/mep4-default.proto

package mep4_default

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSplashesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     int64  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To       int64  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	SensorId string `protobuf:"bytes,3,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
}

func (x *GetSplashesRequest) Reset() {
	*x = GetSplashesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mep4_default_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSplashesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSplashesRequest) ProtoMessage() {}

func (x *GetSplashesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mep4_default_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSplashesRequest.ProtoReflect.Descriptor instead.
func (*GetSplashesRequest) Descriptor() ([]byte, []int) {
	return file_proto_mep4_default_proto_rawDescGZIP(), []int{0}
}

func (x *GetSplashesRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GetSplashesRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *GetSplashesRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type Mep4Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Splashes []*Splash `protobuf:"bytes,1,rep,name=splashes,proto3" json:"splashes,omitempty"`
	Noices   []*Mep4   `protobuf:"bytes,2,rep,name=Noices,proto3" json:"Noices,omitempty"`
}

func (x *Mep4Response) Reset() {
	*x = Mep4Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mep4_default_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mep4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mep4Response) ProtoMessage() {}

func (x *Mep4Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mep4_default_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mep4Response.ProtoReflect.Descriptor instead.
func (*Mep4Response) Descriptor() ([]byte, []int) {
	return file_proto_mep4_default_proto_rawDescGZIP(), []int{1}
}

func (x *Mep4Response) GetSplashes() []*Splash {
	if x != nil {
		return x.Splashes
	}
	return nil
}

func (x *Mep4Response) GetNoices() []*Mep4 {
	if x != nil {
		return x.Noices
	}
	return nil
}

type Splash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Mep4 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Splash) Reset() {
	*x = Splash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mep4_default_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Splash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Splash) ProtoMessage() {}

func (x *Splash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mep4_default_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Splash.ProtoReflect.Descriptor instead.
func (*Splash) Descriptor() ([]byte, []int) {
	return file_proto_mep4_default_proto_rawDescGZIP(), []int{2}
}

func (x *Splash) GetItems() []*Mep4 {
	if x != nil {
		return x.Items
	}
	return nil
}

type Mep4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pm25       int32  `protobuf:"varint,2,opt,name=Pm25,proto3" json:"Pm25,omitempty"`
	Time       uint64 `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	LocationId int32  `protobuf:"varint,4,opt,name=Location_id,json=LocationId,proto3" json:"Location_id,omitempty"`
}

func (x *Mep4) Reset() {
	*x = Mep4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mep4_default_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mep4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mep4) ProtoMessage() {}

func (x *Mep4) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mep4_default_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mep4.ProtoReflect.Descriptor instead.
func (*Mep4) Descriptor() ([]byte, []int) {
	return file_proto_mep4_default_proto_rawDescGZIP(), []int{3}
}

func (x *Mep4) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mep4) GetPm25() int32 {
	if x != nil {
		return x.Pm25
	}
	return 0
}

func (x *Mep4) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Mep4) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mep4_default_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mep4_default_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_mep4_default_proto_rawDescGZIP(), []int{4}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mep4_default_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mep4_default_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_proto_mep4_default_proto_rawDescGZIP(), []int{5}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mep4_default_proto protoreflect.FileDescriptor

var file_proto_mep4_default_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x70, 0x34, 0x2d, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x70, 0x34,
	0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x55, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53,
	0x70, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x22,
	0x6c, 0x0a, 0x0c, 0x4d, 0x65, 0x70, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x08, 0x73, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x70, 0x34, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x2e, 0x53, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x08, 0x73, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x65,
	0x73, 0x12, 0x2a, 0x0a, 0x06, 0x4e, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x70, 0x34, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x2e, 0x4d, 0x65, 0x70, 0x34, 0x52, 0x06, 0x4e, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x22, 0x32, 0x0a,
	0x06, 0x53, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x70, 0x34, 0x5f, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x65, 0x70, 0x34, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x5f, 0x0a, 0x04, 0x4d, 0x65, 0x70, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6d, 0x32,
	0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6d, 0x32, 0x35, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x9c,
	0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x08, 0x53, 0x61,
	0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x70, 0x34, 0x5f, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x70, 0x34, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x20, 0x2e,
	0x6d, 0x65, 0x70, 0x34, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x70, 0x6c, 0x61, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6d, 0x65, 0x70, 0x34, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x4d,
	0x65, 0x70, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a,
	0x0d, 0x2f, 0x6d, 0x65, 0x70, 0x34, 0x2d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mep4_default_proto_rawDescOnce sync.Once
	file_proto_mep4_default_proto_rawDescData = file_proto_mep4_default_proto_rawDesc
)

func file_proto_mep4_default_proto_rawDescGZIP() []byte {
	file_proto_mep4_default_proto_rawDescOnce.Do(func() {
		file_proto_mep4_default_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mep4_default_proto_rawDescData)
	})
	return file_proto_mep4_default_proto_rawDescData
}

var file_proto_mep4_default_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_mep4_default_proto_goTypes = []interface{}{
	(*GetSplashesRequest)(nil), // 0: mep4_default.GetSplashesRequest
	(*Mep4Response)(nil),       // 1: mep4_default.Mep4Response
	(*Splash)(nil),             // 2: mep4_default.Splash
	(*Mep4)(nil),               // 3: mep4_default.Mep4
	(*HelloRequest)(nil),       // 4: mep4_default.HelloRequest
	(*HelloReply)(nil),         // 5: mep4_default.HelloReply
}
var file_proto_mep4_default_proto_depIdxs = []int32{
	2, // 0: mep4_default.Mep4Response.splashes:type_name -> mep4_default.Splash
	3, // 1: mep4_default.Mep4Response.Noices:type_name -> mep4_default.Mep4
	3, // 2: mep4_default.Splash.items:type_name -> mep4_default.Mep4
	4, // 3: mep4_default.Greeter.SayHello:input_type -> mep4_default.HelloRequest
	0, // 4: mep4_default.Greeter.GetSplashes:input_type -> mep4_default.GetSplashesRequest
	5, // 5: mep4_default.Greeter.SayHello:output_type -> mep4_default.HelloReply
	1, // 6: mep4_default.Greeter.GetSplashes:output_type -> mep4_default.Mep4Response
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_mep4_default_proto_init() }
func file_proto_mep4_default_proto_init() {
	if File_proto_mep4_default_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mep4_default_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSplashesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mep4_default_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mep4Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mep4_default_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Splash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mep4_default_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mep4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mep4_default_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mep4_default_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mep4_default_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mep4_default_proto_goTypes,
		DependencyIndexes: file_proto_mep4_default_proto_depIdxs,
		MessageInfos:      file_proto_mep4_default_proto_msgTypes,
	}.Build()
	File_proto_mep4_default_proto = out.File
	file_proto_mep4_default_proto_rawDesc = nil
	file_proto_mep4_default_proto_goTypes = nil
	file_proto_mep4_default_proto_depIdxs = nil
}
